services:
  postgres:
    image: postgres:17
    container_name: golang-postgres

    environment:
      POSTGRES_DB: golangdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - golang_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "8081:80"

volumes:
  golang_postgres_data: